Demo hometask 1
ntcrckr/tank-software-design pull request #2
Opened 2023-09-20 18:06 UTC by ntcrckr

Мой коммит в итоге оказался поверх вашего, но просто лень сейчас с гитом бороться, чтобы ваш удалить

2023-09-20 18:19 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/Tank.java
> +    public void move(float deltaTime) {
А зачем move то?
Было хорошо updateState, то что там внутри происходит изменение координат – детали реализации. В будем он будет ещё и гореть и тратить бензин и ещё что- нибудь. Но контракт останется прежний – updateState.

2023-09-20 18:19 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/InputController.java
> +    private final Map<Integer, Direction> inputMapping = new HashMap<>();
Опять же, было хорошее название, из которого сразу понятно, что выступает в качестве ключа, а что, в качестве значения. Зачем ухудшили? стало менее понятно.

2023-09-20 18:19 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +            if (!tank.goingToCollide(direction, tree.getCoordinates())) {
Лучше бы подумали как вот это вынести отсюда.

2023-09-20 18:19 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        tank = new Tank(new GridPoint2(1, 1), new GridPoint2(1, 1), Direction.RIGHT, 1f, 0.4f);
А зачем эти все параметры вынесли в конструктор?
Было вроде хорошо, без ненужных параметров в конструкторе.

2023-09-22 06:48 UTC, ntcrckr commented on src/main/java/ru/mipt/bit/platformer/Tank.java
> +    public void move(float deltaTime) {
Справедливо, наверное, у меня была мысль по типу "если он будет делать ещё что-то, то я сделаю ещё один метод для этого функционала и оберну их в updateState", но в общем согласен, поправлю

2023-09-22 06:51 UTC, ntcrckr commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        tank = new Tank(new GridPoint2(1, 1), new GridPoint2(1, 1), Direction.RIGHT, 1f, 0.4f);
Мысль заключалась в том, что в будущем танков будет больше и каждый захочется инициализировать своими параметрами. Или разговор про то, что конструктор вызывается в create(), а не сразу инициализирует поле класса GameDesktopLauncher?

2023-09-22 07:13 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        tank = new Tank(new GridPoint2(1, 1), new GridPoint2(1, 1), Direction.RIGHT, 1f, 0.4f);
Ну мы же выставляем опять наружу все  детали реализации, про destination point, movement progress. Если я первый раз вижу класс- я вообще не пойму что это такое. Зачем мне они параметры?
Если я захочу, чтобы танк куда то поехал после создания, я позову move. Зачем мне указывать значения каких то полей странных?

2023-09-22 07:16 UTC, ntcrckr commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        tank = new Tank(new GridPoint2(1, 1), new GridPoint2(1, 1), Direction.RIGHT, 1f, 0.4f);
То есть, оставить надо только его положение и поворот, а остальные параметры, например, сделать со значениями по умолчанию/убрать из инициализации вовсе?

2023-09-22 10:32 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        tank = new Tank(new GridPoint2(1, 1), new GridPoint2(1, 1), Direction.RIGHT, 1f, 0.4f);
Ну да, как и было изначально, собственно

2023-09-24 21:00 UTC, iagoshkov requested changes

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        Direction direction = inputController.getDirection();
Нарушен OCP. Как мне добавить в будущем, например, стрельбу по "пробелу"?

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        drawGraphics();
Вот вам глядя сюда понятно в чем разница между drawGraphics и renderGame?
Если не видеть ни разу эти методы и не заглядывать в их реализацию?

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +    private void drawGraphics() {
т.е. drawGraphics ничего не draw?

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        drawTextureRegionUnscaled(batch, playerGraphics, playerRectangle, tank.getRotation());
OCP совсем нарушен. А как мне добавлять сюда другие танки? А новые препятствия? А самолеты?

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/InputController.java
> +    public Direction getDirection() {
ну вот стрельбу по "пробелу" сюда не добавить уже?OCP?

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/Obstacle.java
> +public class Obstacle {
Тут вроде норм

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
>  public class GameDesktopLauncher implements ApplicationListener {
Ну тут SRP нарушен же явно. Какие вы можете найти причины для изменения этого класса?
Она одна? Интересно, какая? )

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
>  public class GameDesktopLauncher implements ApplicationListener {
Собственно это основная проблема во всем PR.

2023-09-24 21:00 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
>  public class GameDesktopLauncher implements ApplicationListener {
Или тут второго ДЗ еще нет?

2023-09-25 13:08 UTC, ntcrckr commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
>  public class GameDesktopLauncher implements ApplicationListener {
Да, это пока только первый) Второй в другой ветке, пока не пушил

2023-09-25 19:58 UTC, merged